# Generated by Django 5.2 on 2025-10-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_run_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
